[package]
name = "transantlator"
version = "0.1.0"
authors = ["Igor Matuszewski <Xanewok@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
getopts = "0.2"
failure = "0.1"
petgraph = "0.4"